### ISSUE TITLE
null_model without covariates

### ISSUE THREAD

**Issue by akmanning** [manning-lab/topmed-t2d-glycemia-public#42]
The null model script fails when no covariates are specified. The script should fit the null model with no covariates.
https://portal.firecloud.org/#workspaces/amp-t2d-op/topmed-freeze5b-t2d-pilot/monitor/cd08308f-9a5b-4b6f-bb70-bfcf0f68f678

**Comment by tmajaria** [comment]
this has been fixed in branch issue_42
