### ISSUE TITLE
cautionary note on wgsaparsr version 3

### ISSUE THREAD

**Issue by bheavner** [manning-lab/topmed-t2d-glycemia-public#9]
`parse_to_file()` in version 3 of wgsaparsr doesn't currently take the `desired_columns` or `to_split` arguments - I didn't realize it was being used yet, so hard-coded the column names we're parsing at the DCC.

You're good at the moment by using the specific version - `devtools::install_github("UW-GAC/wgsaparsr@2.0.1.4")`, and that should remain okay, but I will be adding another function for parsing selected columns in the future.

I'll comment on this issue when I get to the new function, but thought I'd give the heads up that you probably shouldn't try to use version 3 since it'll break your code.

**Comment by bheavner** [comment]
(I've added this as an issue to WGSAParsr - [https://github.com/UW-GAC/wgsaparsr/issues/53](https://github.com/UW-GAC/wgsaparsr/issues/53) )

**Comment by tmajaria** [comment]
Yes, I ran into the problem with version 3. Thanks for adding the issue to the wgsaparsr repo. Glad that functionality will be kept.

**Comment by bheavner** [comment]
FYI - this can be done again with wgsaparsr v5.0.0. Don't be too quick to implement it - we're bug checking now, so there may be some point releases in the next 2 weeks, but I hope it should behave well.
